// Thea2 spine gate plugin — S1.5(b), P-SPINE-1 (M21), repo-tracked at
// spine/plugin/ and .opencode/plugin compatible (a plugin is a TS module
// exporting its hooks; drop this directory into .opencode/plugin/ or point the
// spine agent config at it).
//
// 'tool.execute.before' fires before EVERY tool execution (built-ins, MCP, and
// task calls alike — source-verified 2026-09-03). The hook:
//   - vetoes calls the static permission layer cannot express (relational
//     predicates: owner-arg chat locks, secret-arg scans, explicit denies),
//   - emits a `gate.rejected` event for EVERY veto (and every fail-open) via a
//     loopback POST to thead's event endpoint (path /spine/gate-events, URL in
//     the env named by rules.eventUrlEnv) — the L0 event itself is written by
//     thead's bridge (lands elsewhere; the plugin only reports),
//   - fail-open rules (rules.failOpenRuleIds) emit but never veto — a style tic
//     must never eat a real reply,
//   - unknown tools deny, always.
//
// This file is SELF-CONTAINED by design: it runs under the spine's own runtime
// (Bun), not under thea2's vitest/tsconfig umbrella, so it imports node
// builtins only — no src/ imports, no zod. The rules JSON is generated by
// src/spine/gates.ts (writeSpineGateFiles) from inhibitions.yaml at compose
// time; secret VALUES arrive via env (rules.secretsEnv), never in the repo.

import { readFileSync } from 'node:fs';
import * as http from 'node:http';
import * as https from 'node:https';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

/** Mirrors src/spine/gates.ts SpineGateRules — kept structurally identical, not imported. */
export interface GateRules {
  version: 1;
  allowTools: string[];
  rules: Array<
    | { kind: 'deny'; tool: string; ruleId: string }
    | { kind: 'owner-arg'; tool: string; ruleId: string; arg: string; ownerChatId: string }
    | { kind: 'secret-args'; tool: string; ruleId: string }
  >;
  failOpenRuleIds: string[];
  secretsEnv: string;
  eventUrlEnv: string;
}

/** The gate event the plugin emits — one per veto AND per fail-open. */
export interface GateRejectedEvent {
  kind: 'gate.rejected';
  tool: string;
  ruleId: string;
  resolution: 'veto' | 'fail-open';
  /** Wall-clock ms from the spine's own runtime — the plugin is outside the injected-clock law. */
  ts: number;
}

/** The thead endpoint path the event URL must point at (designed here, served by thead elsewhere). */
export const GATE_EVENT_PATH = '/spine/gate-events';

export const loadGateRules = (dir: string): GateRules => {
  const raw = JSON.parse(readFileSync(join(dir, 'gate.rules.json'), 'utf8')) as GateRules;
  if (raw.version !== 1 || !Array.isArray(raw.allowTools)) {
    throw new Error(`spine-gate: gate.rules.json in ${dir} is not a v1 rules file`);
  }
  return raw;
};

const postWith = (mod: typeof http | typeof https) => (urlStr: string, body: string): Promise<void> =>
  new Promise((resolve) => {
    try {
      const url = new URL(urlStr);
      const req = mod.request(
        {
          hostname: url.hostname,
          port: url.port,
          path: `${url.pathname}${url.search}`,
          method: 'POST',
          headers: { 'content-type': 'application/json', 'content-length': Buffer.byteLength(body) },
          timeout: 2000,
        },
        (res) => {
          res.resume();
          res.on('end', () => resolve());
          res.on('error', () => resolve());
        },
      );
      req.on('error', () => resolve()); // a broken event sink never blocks the gate
      req.on('timeout', () => {
        req.destroy();
        resolve();
      });
      req.end(body);
    } catch {
      resolve();
    }
  });

const postHttp = postWith(http);

/** Fire-and-forget POST of one gate event. Errors resolve — never throw. */
export const postGateEvent = (url: string, event: GateRejectedEvent): Promise<void> => postHttp(url, JSON.stringify(event));

const isPlainObject = (v: unknown): v is Record<string, unknown> => typeof v === 'object' && v !== null && !Array.isArray(v);

/** Mirrors M12's arg walk: strings, array items, object values — and object KEYS. */
const someArgText = (value: unknown, pred: (text: string) => boolean): boolean => {
  if (typeof value === 'string') return pred(value);
  if (Array.isArray(value)) return value.some((item) => someArgText(item, pred));
  if (isPlainObject(value)) {
    return Object.entries(value).some(([key, v]) => pred(key) || someArgText(v, pred));
  }
  return false;
};

/** Exact name, or a trailing-'*' prefix rule ('mcp*' matches every MCP tool). */
const toolMatches = (pattern: string, tool: string): boolean =>
  pattern.endsWith('*') ? tool.startsWith(pattern.slice(0, -1)) : pattern === tool;

export interface GateHookDeps {
  rules: GateRules;
  /** The secret VALUES to scan args for — env-injected, never in the rules file. */
  secrets?: readonly string[] | undefined;
  /** Injectable poster (tests record; prod posts to thead's event endpoint). */
  post?: ((event: GateRejectedEvent) => Promise<void>) | undefined;
  now?: (() => number) | undefined;
}

export type GateHook = (input: { tool: string }, output: { args: unknown }) => Promise<void>;

/**
 * The pure hook core: same semantics as the plugin, injectable poster/secrets —
 * this is what the replay tests drive (`gate-veto-blocks-a-tool-call-in-replay`,
 * `every-veto-emits-a-gate-event`).
 */
export const makeGateHook = (deps: GateHookDeps): GateHook => {
  const allowed = new Set(deps.rules.allowTools);
  const failOpen = new Set(deps.rules.failOpenRuleIds);
  const post = deps.post ?? (async (event) => postGateEvent(eventUrl(deps.rules), event));
  const now = deps.now ?? (() => Date.now());
  const secrets = deps.secrets ?? resolveSecrets(deps.rules.secretsEnv);

  const event = (tool: string, ruleId: string, resolution: 'veto' | 'fail-open'): GateRejectedEvent => ({
    kind: 'gate.rejected',
    tool,
    ruleId,
    resolution,
    ts: now(),
  });

  return async (input, output) => {
    const tool = input.tool;
    const veto = async (ruleId: string, why: string): Promise<never> => {
      await post(event(tool, ruleId, 'veto'));
      throw new Error(`[INHIBITION:${ruleId}] ${why}`);
    };
    const failOpenNote = async (ruleId: string): Promise<void> => {
      await post(event(tool, ruleId, 'fail-open'));
    };

    // unknown tools deny — the tool must be in the spine allowlist to exist here
    if (!allowed.has(tool)) {
      await veto('unknown-tool-deny', `tool '${tool}' is not in the spine allowlist — deny by default`);
    }

    for (const rule of deps.rules.rules) {
      if (!toolMatches(rule.tool, tool)) continue;
      if (failOpen.has(rule.ruleId)) {
        // fail-open stays fail-open: the event emits, the call proceeds
        await failOpenNote(rule.ruleId);
        continue;
      }
      if (rule.kind === 'owner-arg') {
        const args = output.args;
        if (!isPlainObject(args) || args[rule.arg] !== rule.ownerChatId) {
          await veto(rule.ruleId, `args.${rule.arg} must be the owner chat id`);
        }
        continue;
      }
      if (rule.kind === 'secret-args') {
        const leaked = secrets.find((s) => someArgText(output.args, (t) => t.includes(s)));
        if (leaked !== undefined) {
          await veto(rule.ruleId, 'a runtime secret value must never ride tool arguments');
        }
        continue;
      }
      // rule.kind === 'deny'
      await veto(rule.ruleId, `denied by rule '${rule.ruleId}'`);
    }
  };
};

const eventUrl = (rules: GateRules): string => process.env[rules.eventUrlEnv] ?? '';

/** Secret values ride the spine child's env (colon-separated), never the repo. */
export const resolveSecrets = (secretsEnv: string): string[] =>
  (process.env[secretsEnv] ?? '')
    .split(':')
    .map((s) => s.trim())
    .filter((s) => s !== '');

/**
 * The plugin entry, as OpenCode loads it: returns the hook table. The rules
 * file sits beside this module (generated at compose time).
 */
const gatePlugin = async (context?: { directory?: string }): Promise<Record<string, GateHook>> => {
  const dir = context?.directory ?? dirname(fileURLToPath(import.meta.url));
  const rules = loadGateRules(dir);
  const hook = makeGateHook({ rules });
  return { 'tool.execute.before': hook };
};

export default gatePlugin;
